name: Pre-Release

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

env: 
  TARGET_VERSION: 8.1.0


jobs:

  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: biz-ecosystem-logic-proxy
          tags: ${{ github.sha }} ${{ TARGET_VERSION }}-PRE
          dockerfiles: |
            ./docker/Dockerfile
          context: ./

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/fiware
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}